<?xml version="1.0" ?>
<robot name="box_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find box_bot_description)/robot/materials.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/properties.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/macros.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_body.xacro" />
  <xacro:include filename="$(find box_bot_description)/robot/box_bot.gazebo" />
  <xacro:include filename="$(find box_bot_description)/robot/sensors.xacro" />

  <xacro:box_bot_body_with_meshes parent_name="${base_name}"/>
  
  <xacro:link_wheel name="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" parent="${base_name}" child="right_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" />

  <xacro:link_wheel name="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" parent="${base_name}" child="left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" />


  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  <xacro:caster_wheel parent="chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  
  <xacro:camera_rgb parent_name="${base_name}" sensor_name="rgb_camera" origin_xyz="${base_box_x/ 1.9} 0.0 ${base_box_x / 2.0}" camera_ROLL="0.0" camera_PITCH="0.0" camera_YAW="0.0"/>
  <xacro:laser_scan parent_name="${base_name}" sensor_name="laser_scan" origin_xyz="0.0 0.0 ${base_box_x / 2.0}" sensor_YAW="1.57"/>
  <xacro:block_laser_scan parent_name="${base_name}" sensor_name="block_laser_scan" origin_xyz="${base_box_x/ 1.9} 0.0 ${base_box_x / 2.0}" sensor_YAW="1.57"/>
  


</robot>
